export enum MotivoCancelamento {
  CANCELADO_PELO_PORTADOR_CARTAO_DANIFICADO,
  CANCELADO_PELO_PORTADOR_PERDA,
  CANCELADO_PELO_PORTADOR_ROUBO,
  CANCELADO_POR_SUSPEITA_FRAUDE,
  CANCELADO_PELA_INSTITUICAO_EMISSORA,
  CANCELADO_REEMISSAO
}