export enum CartaoTipo {
  DEBITO_SEM_CHIP,
  CREDITO_SEM_CHIP,
  CREDITO_SEM_CHIP_INTERNACIONAL,
  CREDITO_COM_CHIP,
  CREDITO_COM_CHIP_INTERNACIONAL,
  CREDITO_COM_CHIP_RFID,
  CREDITO_COM_CHIP_RFID_INTERNACIONAL,
}